### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-thumbnails#1]
[HBum187 on reddit asks](https://www.reddit.com/r/emulation/comments/4ef1mf/nointro_box_art_snaps_and_titles/d21bw7d?context=3):

>  So...how do we use these?

**Comment by Kivutar** [comment]
Like this http://www.lakka.tv/doc/Game-Thumbnails/

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-thumbnails/pull/57
