### ISSUE TITLE
SGX, MSX2 and Satellaview don't show

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/libretro-thumbnails#10]
NEC Supergrafx, Microsoft MSX2 and SNES Satellaview thumbnails aren't showing here, with a 2016-01-03 no-intro set.

win7 x64

**Comment by sergiobenrocha2** [comment]
Should be fixed on #11 

There's no Satellaview thumbnails yet in this repo.

**Comment by sergiobenrocha2** [comment]
There's a problem with the title pictures, some of them are not showing. What's the true resolution of MSX and MSX2 ?

fMSX gives me 272x228
blueMSX gives me 272x240

The wiki says it's:
256×192 for MSX
512×212 (16 colours out of 512) and 256×212 (256 colours) for MSX2

The thumbnails are 544x480, 2x the blueMSX resolution

**Comment by Tatsuya79** [comment]
Yes it should be something like 256×192 for MSX (+ overscan I assume?).
Some infos here: http://www.faq.msxnet.org/msx1.html
http://www.faq.msxnet.org/msx2.html

For Satellaview, they are in the SNES folder: all those with (BS) at the end.

**Comment by sergiobenrocha2** [comment]
In Video, Crop Overscan = ON, I don't know what's going on here.

**Comment by Tatsuya79** [comment]
For Satellaview the files are there but they're not in the dat.

That's working for SGX and MSX2 now, thank you.

**Comment by sergiobenrocha2** [comment]
Satellaview is not working because it's a different platform, the thumbnails should be located at "Nintendo - Satellaview". There's a separate dat for it too.

**Comment by Tatsuya79** [comment]
I made the Satellaview folder with the last dat from the no-intro website.
Tested working here (didn't check every picture yet though).

If anyone can add it, Github doesn't want it in drag&drop upload for whatever reason:
https://mega.nz/#!lxN3WLzQ!A9VjGPuNuxizK3SRd8PJ29nnhVP9MLoY_9oY6ySXVJY

You can also remove every (BS) file from the SNES folder.

**Comment by Tatsuya79** [comment]
I did the Sufami Turbo too, tested working:
https://mega.nz/#!d9UhCbDZ!IvUTFFFZxxGaz2a2AjT1Nx9vVtxbfozF4TYPg1DZSns

Then files with (ST) at the end can be killed from the SNES folder.
