### ISSUE TITLE
Adding new files creates a new folder with % instead of spaces?

### ISSUE THREAD

**Issue by Axiphel** [libretro/libretro-thumbnails#112]
I added some box arts last night and for some reason instead of being added into Nintendo - Nintendo DS Decrypted it creates an entirely new folder Nintendo%20-%20Nintendo%20DS%20Decrypted 

I'm doing the same thing I've always done which is just drag and drop and commit.

**Comment by Alcaro** [comment]
Are you sure that's a bug on our end, as opposed to GitHub itself, or possibly even your browser?

**Comment by Axiphel** [comment]
Not sure, really. I'll try with a different browser.

**Comment by Axiphel** [comment]
Just tried it with Edge and it does the same thing.

**Comment by fr500** [comment]
don't use the web interface, use a git client.
