### ISSUE TITLE
Sega - Master System - Mark III - Named_Boxarts

### ISSUE THREAD

**Issue by lollo78** [libretro/libretro-thumbnails#13]
I would like to push the Sega - Master System - Mark III (incomplete). Before to do that, please tell me the size I have to use. Mine are 480x680 pixel. Is fine for you or I have to reduce the size?

**Comment by twinaphex** [comment]
Go for it I guess.

**Comment by lollo78** [comment]
I still have an issue to clone correctly the repository:
https://github.com/libretro/libretro-thumbnails/issues/9#issuecomment-215991445
To avoid problems, please guys, could you push this for me?
https://www.dropbox.com/s/xhr6zzw34tmike0/Sega%20-%20Master%20System%20-%20Mark%20III%20-%20Named_Boxarts.zip?dl=0
Thx

**Comment by sergiobenrocha2** [comment]
@lollo78 --> https://github.com/libretro/libretro-thumbnails/issues/3#issuecomment-215777878

**Comment by sergiobenrocha2** [comment]
If 480x680 is the original resolution, then it's ok I guess. But if you have large pictures, then use 512 width for the most common, 256 for the others (to save bandwidth and space).

**Comment by lollo78** [comment]
@Kivutar 
Could you push this for me?
Thx

**Comment by RobLoach** [comment]
These are in, could close this issue.

**Comment by lollo78** [comment]
yes I pushed it some months ago, but forgot to close the issue.
sorry
