### ISSUE TITLE
Submission: MAME thumbnails

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-thumbnails#137]
This thumbnail set began in a different form as a pull request regarding MAME 2003 thumbnails. That background along with the script I used to rename the thumbnails to RetroArch naming convention is in the now-closed pull: https://github.com/libretro/libretro-thumbnails/pull/80

The linked thumbnail sets below are derived from the arcadeitalia database. (arcadeitalia uses the same Progetto-SNAPS dat file for reference as do the libretro cores.) I began with the arcadeitalia MAME 0.159 (MAME 2014 core) set, and added in support for name variations for the other 'frozen' MAME cores (MAME 2000, 2003, 2010). This 'omnibus' MAME thumbnail set is only a 7% increase in total archive size from MAME 2014 alone.

Thumbnails that started as less than 512px wide remain at their original resolution for RetroArch to scale up. Thumbnails that were larger than 512px wide are scaled down to 512px. 

**'MAME Omnibus Thumbnails' (MAME 2000/2003/2010/2014 name variations)**
- Named_Boxarts: https://mega.nz/#!0hMjQBzD!b2xztJUmz0KxTRvs8ZLR-BhjdVOWMe0TeM4OzjpKQtM
- Named_Snaps (v2) https://mega.nz/#!YxkAyCqK!43wNbAzCcSd3dTOYdGk6imKagXWLvjCoHLH9KfmJi58
- Named_Titles (v2) https://mega.nz/#!FxkikLxJ!n32J6V8UIZtyVw93ypytEpuDo_SLADEiukgGMitQzuI

**Comment by cudencuden** [comment]
hey.....i was having issue using lakka online thumbnail downloader because the zip file became too big...i will just download from your mega links then..thanks..

**Comment by markwkidd** [comment]
Apologies for the clutter with this PR. I'm going to regroup and try this with a smaller subset of the MAME thumbnail set.

**Comment by Redemp** [comment]
:)

**Comment by markwkidd** [comment]
Let's take another shot with a new PR: **https://github.com/libretro/libretro-thumbnails/pull/145**
