### ISSUE TITLE
Magnavox - Odyssey2

### ISSUE THREAD

**Issue by lasers** [libretro/libretro-thumbnails#162]
`Magnavox - Odyssey2/Named_Boxarts` - Missing
`Magnavox - Odyssey2/Named_Snaps` - Broken
`Magnavox - Odyssey2/Named_Titles` - Broken

**Comment by RobLoach** [comment]
https://github.com/RobLoach/libretro-thumbnails-check/blob/master/out/Magnavox%20-%20Odyssey2.txt

Some of the Snaps/Titles could be incorrect.

**Comment by lasers** [comment]
Closing in favor of link above. Regularly updated and all. 🦁
