### ISSUE TITLE
Sources for Atari 2600 thumbnails

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-thumbnails#184]
I have been meaning to devote some time to an Atari 2600 thumbnail collection but I haven't yet had the chance. Now with the new database using No-Intro style game names for this system, I thought I'd at least share my starting points in case anyone else is also compiling a list of source images.

Are there any other good sources for these thumbnails? What about a protocol for naming them the same as the playlist names?

Here's what I've found so far:

**Official Stella Emulator 2600 Snap Library**
Homepage: http://stella.sourceforge.net/screenshots.php
Full collection download: https://sourceforge.net/projects/stella/files/stella/3.6/ (look for the latest file starting with "stella-snapshots")

**Typhon's Atari Box Art Collection (libretro forums)**
https://libretro.com/forums/showthread.php?t=7490

In order to set things up Typhon recommends the **Bulk Rename Utility** in the forums but I haven't tried it myself: http://www.bulkrenameutility.co.uk/Features.php

**Comment by markwkidd** [comment]
@RobLoach I see that you added some boxart for Atari 2600 just a few days ago. I am not surprised, somehow. It may be that this issue is not needed after all! :)

**Comment by RobLoach** [comment]
Updated the [Atari 2600 thumbnails report](https://raw.githubusercontent.com/RobLoach/libretro-thumbnails-check/master/out/Atari%20-%202600.txt) from [libretro-thumbnails-check](https://github.com/RobLoach/libretro-thumbnails-check/tree/master/out). Looks like there are some [mismatches](https://github.com/RobLoach/libretro-thumbnails-check/blob/master/out/Atari%20-%202600%20Orphans.txt), and it's missing the snaps/titles.

Could use some work!

**Comment by RobLoach** [comment]
@RetroUp may know some sources.

**Comment by RetroUp** [comment]
I'll upload a set of named images in a day or two.

I think Bulk Rename Utility just renames files. It doesn't match.

Software that will work. FatMatch, Tur-Match, Game Set Match, FuzzyRename, Generic Artwork Renamer, Shot Reporter.

**Comment by RetroUp** [comment]
https://github.com/RetroUp/libretro-thumbnails/tree/master/Atari%20-%202600

I added a couple extra folders that I did not know if you wanted or not.

The AVI and FLV are identical videos, just different formats. They are over compressed IMO. Higher quality videos are available elsewhere.

The PNG images are optimized. Mainly with pngquant. About a 70% filesize reduction without quality loss. I don't know what your policy is on pngquant but I see no reason not to use it. > https://github.com/libretro/libretro-thumbnails/issues/54

The manuals are PDFs and also optimized for filesize.

There are still some missing files, but I am finished. If someone wants to complete it that would be awesome.

**Comment by RetroUp** [comment]
I am new to github. Should I create a pull request for these or wait for someone to review the additional folders and compression first?

**Comment by RobLoach** [comment]
Nicely done on the [Atari 2600 Art libretro-thumbnail fork](https://github.com/RetroUp/libretro-thumbnails/tree/master/Atari%20-%202600) that you've put together.

I believe libretro-thumbnails only needs Named_Boxarts, Named_Titles, and Named_Snaps.

One way you could handle this is cherry-picking the commits into a new branch...

```
cd libretro-thumbnails
git checkout 2a1d8402f3e344dd25d4e366a01dba7300e57893
git checkout -b atari-2600-arts
git cherry-pick 58a9dbe8f4d51fac27d9d4bb68ff2c14d6a2e955 eb86e8becd3896ab75559615f58046aa79ca3781 75b8c12234257b32a4fce379226b14e6cd8c0388 d535c823cade478c1ae2048e3161a6b151e45ca2
git push origin atari-2600-arts
```

**Comment by markwkidd** [comment]
Seems like I can close this issue now! 😍
