### ISSUE TITLE
Invalid filesystem characters in game names

### ISSUE THREAD

**Issue by leiradel** [libretro/libretro-thumbnails#19]
In a conversation with @twinaphex  and @Alcaro, we concluded that we must either change game names that contain the characters \/<>&?"|: (and anything outside the 32-126 range), or sanitize the game name to produce a file name that is valid (i.e. URL-encode them or something like it.)

Right now ZX Spectrum game names are being changed to avoid those characters, so games like "Dan Dare: Pilot of the Future" become "Dan Dare_ Pilot of the Future"

**Comment by Kivutar** [comment]
Yes. It also affects arcade roms. Let agree on a serie of replacements for these. We should try to end up with names that looks good. No-intro have some rules about the names that we should follow.

Encoding the name would cause problems. For now the filename and the dat name have always matched. We don't want to loose that.

**Comment by leiradel** [comment]
Why encoding the name would cause problems? The only problem I can see is that we'd have to convert all the files already in the thumbnails server, but we can do a batch rename, no?

I was thinking in URL-encode the game names and use that as the file names. We only have to do that when saving a downloaded image, and when reading it from the file system. All images in the server would have been already renamed.

**Comment by Kivutar** [comment]
I wasn't talking about a technical problem. I just think it would be sad to loose the consistency we currently have between file names, rom names, savestates, savefiles... In order to not raise the barrier for external contributions to thumbnails.

If we keep things simple as they are, we can get the help of dozens of gamers who have no idea about what is percent encoding. They just drag and drop the image on the github folder, and that creates a PR.

Now I understand that my proposal of fixing some names in the DAT is also a barrier to contributions. But at least it affects a minority of systems like Arcade and ZX Spectrum.

I would like these images to be used outside of RA. As a wider community effort, at the scale of No-Intro. That's why I maintained compatibility with https://screenshotpalace.wordpress.com/no-intro-screenshot-reloaded/

Just in case some tools (that I'm not aware of) uses those thumbs.

**Comment by leiradel** [comment]
Sorry, I wasn't aware that you have plans for this outside the libretro ecosystem, and I agree that encoding names makes it difficult for others to contribute. We could create some tools, both command line and online, to help contributors, but ideally they wouldn't have to do anything like that.

Well, so lets come up with a rule to rename game names and stick with it. I was already doing that anyway, replacing invalid filesystem characters with dashes. I think dashes blend within names better than underlines.

**Comment by Kivutar** [comment]
No problem. I'm not 100% against encoding either. If others agree with you.

In XMB, I currently have this for the thumbnails:

    tmp = string_replace_substring(entry.path, "/", "-");

It was added for FBA thumbs, and was enough to cover all of them, if I recal correctly.

Except the 2 names that are too long for windows.

**Comment by leiradel** [comment]
Alcaro said this should cover all characters that can cause problems when present in file names: \/<>&?"|:*

For the databases I'm updating, I've already seen the colon, the question mark, and the asterisk, but I think we should cover all our bases.

**Comment by stubl** [comment]
yeah I think we should always go with the latest no-intro and MAME naming conventions, as that is what everyone has, and thats consistent, and can work for many different mediums

the project may also be expanded into cheats and game info txt files, etc. with that

**Comment by leiradel** [comment]
@stubl where can I find no-intro and MAME conventions for file names?

**Comment by stubl** [comment]
[http://datomatic.no-intro.org/?page=download](http://datomatic.no-intro.org/?page=download)
[http://www.progettosnaps.net/dats/](http://www.progettosnaps.net/dats/)

finding complete sets for no-intro or MAME shouldnt be hard on the internet either... especially if you search a certain "internet archive" site

**Comment by stubl** [comment]
having said the above, I would in no way recommend doing all of MAME, and theres already projects covering that

I just suggest MAME or FBA or something like that, only for the particular systems which no-intro does not cover already

**Comment by stubl** [comment]
I should elaborate, I believe no-intro should be priority, but for cores that arent covered by any no-intro dats, it can be FBA or MAME, for specific

**Comment by markwkidd** [comment]
I'm pretty interested in this question, specifically in regards to MAME. I'm creating a set of thumbnails for the MAME 2003 Reference Set ROMs, and I'm planing on basing the playlist (and therefore the image filenames) on this MAME playlist generation script:

`;### Replace forbidden characters in the game name with something suitable for a file`
`datname1 := RegExReplace(datname1, "[/\?<>\\:*\|]","")`
`datname1 := RegExReplace(datname1, "&apos;","'")`
`datname1 := RegExReplace(datname1, "&amp;","&")`
`datname1 := RegExReplace(datname1, "\.$","") `

Is that RegEx replacement going farther than it needs to be? I notice that this MAME generator it is replacing characters that @Kivutar didn't replace in the Final Burn Alpha playlist generator.

**Comment by leiradel** [comment]
I think the final word is to swap all occurrences of **\/<>&*?"|:** for **_**.

**Comment by markwkidd** [comment]
Great, thanks!

**Comment by markwkidd** [comment]
Maybe this horse is already out of the barn, but if we're already swapping, why not swap `&` with `and`?

**Comment by Alcaro** [comment]
s/&/ and /
s/  / /

**Comment by leiradel** [comment]
Of course it's not difficult, the problem is that if we start adding rules to produce pretty filenames we could end up with a mess of rules to accommodate all special cases.

**Comment by markwkidd** [comment]
I don't know why I posted that question -- consider it thinking out loud. :) '&' will become '_'

Thanks for the help. I'm pretty sure I've reworked that script now in order to produce playlists and thumbnails for MAME according to the same naming convention as the FB Alpha content. I may post again once I have time to test the script more thoroughly.

**Comment by markwkidd** [comment]
This issue should be addressed by 1) a PR that has been merged into libretro/RetroArch: https://github.com/libretro/RetroArch/commit/5be99842b5f664ed1274c0b6918712bdac4241c5

As well as 2) a PR that is pending for the thumbnail repo: https://github.com/libretro/libretro-thumbnails/pull/144

Between the two PRs, RetroArch will 1) adopt No-Intro filename standards for thumbnails with 'nice' names preserved in the playlist, and 2) the existing thumbnail filenames will have prohibited characters changed to _

**Comment by lasers** [comment]
Close this?
