### ISSUE TITLE
SFC clones of SNES games?

### ISSUE THREAD

**Issue by kwyxz** [libretro/libretro-thumbnails#191]
While checking out the latest No-Intro datfiles for the Super Nintendo romset I have stumbled upon new entries like this:

http://datomatic.no-intro.org/index.php?page=show_record&s=49&n=1114

There is now a bunch of games qualified as `(Japan) (En)`

The No-Intro website calls them clones of European games, but I'm quite puzzled. Does anyone have any idea what they are? Where are these coming from? As far as I know Japanese SFC and European SNES are not compatible because of a region-locking chip incorporated in the cartridges so I am left wondering what these clones are about.

Now in regards to the boxarts, what's the consensus with these clones, should we use Japanese or European boxarts? (I'm leaning towards Japanese but ymmv)

**Comment by hizzlekizzle** [comment]
I assume these are games that were made by Western studios and released in USA/PAL-land before being localized for Japanese release. I would use the Japanese boxarts.

**Comment by kwyxz** [comment]
Thanks for your answer! I will be using the Japanese boxarts.
Regarding the origin of the games, it's very unclear : a lot of them indeed are made by western studios but there is a bunch of 100% Japanese games as well, for example:

```
Human Grand Prix III - F1 Triple Battle (Japan) (En).png
Human Grand Prix II (Japan) (En).png
Human Grand Prix IV - F1 Dream Battle (Japan) (En).png
Human Grand Prix (Japan) (En).png
HyperZone (Japan) (En).png
Jaleco Rally Big Run - The Supreme 4WD Challenge (Japan) (En).png
Mario to Wario (Japan) (En).png
```

Puzzling indeed.

**Comment by hizzlekizzle** [comment]
Yeah, definitely could be.

**Comment by RobLoach** [comment]
Would symlinks work for clones?

**Comment by kwyxz** [comment]
Are symlinks even preserved on Github? (I use hardlinks on my personal repo)

**Comment by Alcaro** [comment]
Git supports symlinks, so GitHub does too. Not sure about hardlinks.

**Comment by kwyxz** [comment]
Good to know! I'm quite positive hardlinks are not supported, hence my question.

**Comment by RobLoach** [comment]
Curious to see if it would work. Symlinks would save a lot of disk space, and ease maintenance across all the clones. My only concern would be if the buildbot preserves them.

**Comment by kwyxz** [comment]
I could give it a try with the Japanese clones mentioned in this ticket. Like you said, using symlinks could save a lot of spacem, things like Final Burn Alpha / MAME would benefit a huge deal from it.

**Comment by kwyxz** [comment]
So I gave it a try. All "En" clones of Japanses games in https://github.com/kwyxz/libretro-thumbnails/tree/master/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/Named_Boxarts were replaced by symlinks. 

I am assuming it wouldn't be a problem with Linux or Mac OS X systems. Anyone running Windows willing to check out if it breaks everything?

**Comment by RobLoach** [comment]
Tested in RetroArch, and the menu resolves the symlinks correctly.
```
RetroArch: Frontend for libretro -- v1.3.6Compiler: GCC (5.4.0) 64-bitBuilt: Dec 15 2016
Linux 4.4.0-57-generic #78-Ubuntu x86_64
```

**Comment by kwyxz** [comment]
Closing this, I got the answers I needed! :)
