### ISSUE TITLE
Guidelines

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/libretro-thumbnails#3]
Some guidelines should be useful.
- Default size (width = 256 ? too small for big size TVs... the 32X boxarts seems to be ok, 495 px width) 
- Source of the Pictures (thecoverproject? thegamesdb? GameFAQs?)

Edit: GameFAQs has some too (low resolution it seems)
Edit2: gamescanner.org too
Edit3: segaretro

**Comment by Kivutar** [comment]
We have to keep the size of this repo small. Previously it was 50GB+. After I resize all, we end up with 3GB. And when it will be complete, is should be like 20GB or something like that.

RA have a linear filter for the images. And big TVs are not supposed to be watched at a short distance. We should target 1080p in a first time.

**Comment by sergiobenrocha2** [comment]
< kivutar > sergio-br2, the pictures are from thegamesdb

**Comment by sergiobenrocha2** [comment]
@Kivutar what do you think to move to Moby Games & The Cover Project ? See https://github.com/libretro/no-intro-thumbnails/issues/6#issuecomment-214046569

**Comment by Kivutar** [comment]
If the covers are of better quality like you said, then it's a good idea. Do we have a way to know what entries match Moby Games or The Cover Project entries?

**Comment by sergiobenrocha2** [comment]
I'm afraid we will need to see that manually, for each game.

---

As talked on IRC, let's use 512 px for the most famous games, something like 100 for genesis for example.

**Comment by lollo78** [comment]
@twinaphex 
Could you add in Retroarch the support of this compressed PNG?
https://github.com/libretro/Lakka/issues/284#issuecomment-176998255
This will help the users to save a lot of space in their SD/Hard Disk.

**Comment by sergiobenrocha2** [comment]
@davmanypsp, take a look here first.

**Comment by Schroedingers-Cat** [comment]
I collected some boxart from missing European and German psx games and would like to contribute them to RA. What file size and resolution would you appreciate?

**Comment by markwkidd** [comment]
Hi @Schroedingers-Cat and others: There are some updates to the README for this repository which add detail about maximum resolution and filename standards: https://github.com/libretro/libretro-thumbnails/blob/master/README.md

Do those README changes addresses the concerns laid out in this issue?

**Comment by sergiobenrocha2** [comment]
@markwkidd we should add that we maintain only real stuff regarding to box arts. No mock-up / fake art box should be allowed, including those box for beta/proto. Box art for unlicensed stuff should be OK if there is/was real stuff or at least an official artwork from the developer. @Kivutar and I was discussing about this in # lakka

Example of mock-up: https://en.wikipedia.org/wiki/Gley_Lancer#/media/File:Gley_lancer.jpg

**Comment by markwkidd** [comment]
Thanks @sergiobenrocha2 ! There is now a new section of the README to discuss fanmade and mockup boxart.

**Comment by Schroedingers-Cat** [comment]
I think the updated README has all the info one needs to know. This issue can be closed.

**Comment by markwkidd** [comment]
Hi @sergiobenrocha2 -- would you consider this issue addressed and ready to close now?
