### ISSUE TITLE
Sword of Mana (Fr,De) - damaged boxart

### ISSUE THREAD

**Issue by MattiHameister** [libretro/libretro-thumbnails#312]
[The image](https://github.com/libretro/libretro-thumbnails/blob/master/Nintendo%20-%20Game%20Boy%20Advance/Named_Boxarts/Sword%20of%20Mana%20(Europe)%20(Fr,De).png) is just gray at the lower part of the image. It could be replaced by one of the other european images for that game.

**Comment by RobLoach** [comment]
Feel free to fork and then update the image. You can do that directly within the GitHub UI.
