### ISSUE TITLE
(Redump) Convert over Xbox redump database

### ISSUE THREAD

**Issue by twinaphex** [libretro/libretro-thumbnails#314]
@RobLoach and others - 

I'd like to have an XML-to-DAT conversion of redump.org's Xbox database.

**Comment by RobLoach** [comment]
Done:
https://github.com/libretro/libretro-database/blob/master/metadat/libretro-dats/Microsoft%20-%20Xbox.dat

We'll also need build-database https://github.com/libretro/libretro-super/pull/459

**Comment by twinaphex** [comment]
OK - cool.  will add it to libretro-super.
