### ISSUE TITLE
"FB Alpha - Arcade Games" is not extracting on Windows

### ISSUE THREAD

**Issue by Oggom** [libretro/libretro-thumbnails#350]
RetroArch isn't able to extract the thumbnail files from the "FB Alpha - Arcade Games" set on Windows since the OS isn't case sensitive and therefore won't tolerate certain files in the same folder.

For example:
"The King of Fighters '98 - The Slugfest _ King of Fighters '98 - Dream Match Never Ends (Korean board).png"
and
"The King of Fighters '98 - The Slugfest _ King of Fighters '98 - dream match never ends (Korean board).png"
cannot be in the same folder as Windows considers them to share the same filename.

This might also apply to other thumbnail sets, but my slow connection won't allow me to test them all out any time soon.

**Comment by kwyxz** [comment]
These duplicates should never have been there in the first place. I'll look into removing them.

**Comment by kwyxz** [comment]
I have a list of 273 duplicates. Possibly some of these can be renamed instead of removed. This will take me a bit of work.

**Comment by kwyxz** [comment]
I think the latest commit fixed your issue.

**Comment by kwyxz** [comment]
The issue should be fixed in https://github.com/libretro-thumbnails/FB_Alpha_-_Arcade_Games now

**Comment by kwyxz** [comment]
I guess I could just add this repo as a remote and merge to it

**Comment by RobLoach** [comment]
> I guess I could just add this repo as a remote and merge to it

Unfortunately not, since they're in different directories. Best solution may be copy/paste. libretro-thumbnail/libretro-thumbnail will be the final target though, so just make sure that one's good.

**Comment by RobLoach** [comment]
This should be fixed.

**Comment by Oggom** [comment]
Thank you, it seems extract without issues now.
