### ISSUE TITLE
Truncate filenames?

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-thumbnails#4]
When checking out with git, some files cannot be created because they exceed filename length limit:

```
error: unable to create file Nintendo - Game Boy Advance/Named_Boxarts/2 Games in 1 - The SpongeBob SquarePants Movie + SpongeBob SquarePants and Friends in Freeze Frame Frenzy (Europe) (En,Fr,De,Es,It,Nl+En,Fr,De,Es,Nl).txt (File name too long)
error: unable to create file Nintendo - Game Boy Advance/Named_Snaps/2 Games in 1 - The SpongeBob SquarePants Movie + SpongeBob SquarePants and Friends in Freeze Frame Frenzy (Europe) (En,Fr,De,Es,It,Nl+En,Fr,De,Es,Nl).png (File name too long)
error: unable to create file Nintendo - Game Boy Advance/Named_Titles/2 Games in 1 - The SpongeBob SquarePants Movie + SpongeBob SquarePants and Friends in Freeze Frame Frenzy (Europe) (En,Fr,De,Es,It,Nl+En,Fr,De,Es,Nl).png (File name too long)
```

**Comment by Kivutar** [comment]
So what are the filenames of those roms in the no-intro romset?

**Comment by RobLoach** [comment]
It's corectly named, it just appears to be too long for git to handle, at least on my system:
http://datomatic.no-intro.org/?page=show_record&s=23&n=2593

**Comment by Kivutar** [comment]
What is your system?

**Comment by RobLoach** [comment]
Linux Jarvis 4.2.0-35-generic #40-Ubuntu SMP Tue Mar 15 22:15:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ext4

**Comment by Kivutar** [comment]
Ah ok, I didn't know that git had a filename limit :o

**Comment by RobLoach** [comment]
I enabled `core.longpaths = true` in `.gitconfig`.  Haven't seen any problems since... I'll close this for now.
