### ISSUE TITLE
Truncated Directory Listing

### ISSUE THREAD

**Issue by zach-morris** [libretro/libretro-thumbnails#43]
If a directory has more than 1000 images in it, github truncates the listing with an error (ZX Spectrum for example):
"Sorry, we had to truncate this directory to 1,000 files.  7,273 entries were omitted from the list"
Can an xml file or similar be included above a directory to show the contents (title, image url, etc)?

Thanks!

**Comment by Kivutar** [comment]
Hello, this limitation is just a limitation of the web interface of github. But not a limitation of git. If you clone the repository locally, you should be able to see the files.

**Comment by zach-morris** [comment]
True, but if I don't want to clone the entire repo is there a way to know which files are included?
Thanks again

**Comment by Kivutar** [comment]
Is using the search function acceptable?

**Comment by RobLoach** [comment]
This is fixed for me, how 'bout you?

**Comment by zach-morris** [comment]
I've just resorted to getting the entire directory.  Not ideal but thats OK
