### ISSUE TITLE
program to compare files in folders

### ISSUE THREAD

**Issue by stubl** [libretro/libretro-thumbnails#50]
do you use a program to determine differences and the files needed to be changed, to match the latest no-intro DATs?

[I found a program called "SourceGear DiffMerge"](http://www.sourcegear.com/diffmerge/downloads.php)

I put in sega genesis boxarts for 1 folder (file names based on newer no-intro DAT), and sega genesis snaps/titles for the other, and compared the 2, and the program listed the differences

if you select "show peerless" button it will highlight the differences between the files in the folders in purple

you should first batch rename all the .txt extensions to .png, to give a VERY clear comparison [(this is the program I use)](http://www.fastfilerenamer.com/)

I just hope this information proves useful to you, or anyone who needs to compare folders/files and whatnot - perhaps it can make the project easier, and can help with consistency

**Comment by stubl** [comment]
to show an example of the usefulness of this program, I used the above to determine the following genesis snaps are not equal to (the more up to date) boxarts and need to either be added, deleted, or renamed - you need to use the program to tell which is which:

"Peerless File","","[BIOS] Multi-Mega (Europe) (v2.21X) [b].png",""
"Peerless File","[BIOS] Multi-Mega (Europe) (v2.21X).png","",""
"Peerless File","Aaahh!!! Real Monsters (USA) (Beta) (1995-07-07).png","",""
"Peerless File","Beastball (World) (Proto).png","",""
"Peerless File","Bill's Tomato Game (USA) (Proto).png","",""
"Peerless File","Captain Lang (Japan) (En,Ja).png","",""
"Peerless File","","Cross Fire (USA).png",""
"Peerless File","Davis Cup Tennis (Japan).png","",""
"Peerless File","Donald in Maui Mallard (Brazil).png","",""
"Peerless File","Fatal Rewind (Europe).png","",""
"Peerless File","Fatal Rewind (USA, Europe) (Rev A).png","",""
"Peerless File","","Fatal Rewind (USA, Europe).png",""
"Peerless File","FIFA International Soccer (Japan) (En,Ja).png","",""
"Peerless File","Frog Dude (USA) (Proto).png","",""
"Peerless File","GO-NET (Japan).png","",""
"Peerless File","Gunfight 3 in 1 (World) (Unl).png","",""
"Peerless File","HardBall III (USA) (Unl).png","",""
"Peerless File","","HardBall III (USA) (Unl.png",""
"Peerless File","Hook (Europe).png","",""
"Peerless File","Legend of Wukong (World) (Unl).png","",""
"Peerless File","Lufia & the Fortress of Doom (USA) (Proto).png","",""
"Peerless File","Marble Madness (Japan).png","",""
"Peerless File","","Marko (USA).png",""
"Peerless File","","Marko's Magic Football (Europe) (En,Fr,De,Es) (Beta).png",""
"Peerless File","","Marko's Magic Football (Europe) (En,Fr,De,Es).png",""
"Peerless File","Oh Mummy Genesis (World) (Unl).png","",""
"Peerless File","","Out of this World (USA).png",""
"Peerless File","Pac-Panic (Europe).png","",""
"Peerless File","Panorama Cotton (Japan) (Beta) (1993-11-27).png","",""
"Peerless File","Phantasy Star IV (Europe).png","",""
"Peerless File","Pro Action Replay (Europe) (Program) (Unl).png","",""
"Peerless File","","Pro Action Replay (Europe) (Program).png",""
"Peerless File","Pro Action Replay 2 (Europe) (Alt 1) (Program) (Unl).png","",""
"Peerless File","","Pro Action Replay 2 (Europe) (Alt 1) (Program).png",""
"Peerless File","Pro Action Replay 2 (Europe) (Program) (Unl).png","",""
"Peerless File","","Pro Action Replay 2 (Europe) (Program).png",""
"Peerless File","","R.B.I. Baseball 3 (USA).png",""
"Peerless File","Road Rash (Japan).png","",""
"Peerless File","","Simpsons, The - Bart's Nightmare (USA, Europe).png",""
"Peerless File","Slam - Shaq vs. the Legends (USA) (Proto).png","",""
"Peerless File","","Sonic Spinball (Europe).png",""
"Peerless File","Sonic The Hedgehog 2 (World) (Beta) (Alt 1).png","",""
"Peerless File","Sonic The Hedgehog Spinball (Europe).png","",""
"Peerless File","Star Control (USA) (Unl).png","",""
"Peerless File","","Star Control (USA).png",""
"Peerless File","Star Odyssey (World) (Unl).png","",""
"Peerless File","Summer Challenge (USA, Europe) (Unl).png","",""
"Peerless File","","Summer Challenge (USA, Europe).png",""
"Peerless File","","Super Airwolf (Japan).png",""
"Peerless File","Super Daisenryaku (Japan) (Rev A).png","",""
"Peerless File","Super Off Road (USA, Europe) (Unl).png","",""
"Peerless File","","Super Off Road (USA, Europe).png",""
"Peerless File","Test Drive II - The Duel (USA, Europe) (Unl).png","",""
"Peerless File","","Test Drive II - The Duel (USA, Europe).png",""
"Peerless File","Time Trax (USA) (Proto).png","",""
"Peerless File","ToeJam & Earl in Panic on Funkotron (USA) (Beta).png","",""
"Peerless File","Turrican (USA, Europe) (Unl).png","",""
"Peerless File","","Turrican (USA, Europe).png",""
"Peerless File","","Ultraman (Japan).png",""
"Peerless File","Universal Soldier (USA, Europe) (Unl).png","",""
"Peerless File","","Universal Soldier (USA, Europe).png",""
"Peerless File","WarpSpeed (USA) (Unl).png","",""
"Peerless File","","WarpSpeed (USA).png",""
"Peerless File","","Wiz'n'Liz - The Frantic Wabbit Wescue (Europe).png",""

**Comment by stubl** [comment]
I found some more programs that might be helpful to the project

[at this site](http://no-intro.dlgsoftware.net/main.php?modulo=descargas&contenido=tools&lang=1)

**Comment by lasers** [comment]
Close this?

**Comment by RobLoach** [comment]
https://github.com/RobLoach/libretro-thumbnails-check/blob/master/out/README.md#libretro-thumbnails-check-report
