### ISSUE TITLE
Filename conflict with HFS+ filesystem (Mac OS X)

### ISSUE THREAD

**Issue by cfillak** [libretro/libretro-thumbnails#87]
This seems to have only affected a pair of files:
https://github.com/cfillak/libretro-thumbnails/blob/master/Sony%20-%20PlayStation/Named_Boxarts/Alundra%20(USA)%20(V1.1).png

https://github.com/cfillak/libretro-thumbnails/blob/master/Sony%20-%20PlayStation/Named_Boxarts/Alundra%20(USA)%20(v1.1).png

It seems that there are 2 alternate boxarts for this game (Alundra (USA)). Their filenames are:
Alundra (USA) (v1.1).png
Alundra (USA) (V1.1).png

The names are only differentiated by the case of the 'v' or 'V' in the version number. The Mac OS X filesystem HFS+ is case-insensitive but case-preserving, that is it will leave whichever case you use to name files as the outward representation of the filename but under the hood it sees no difference between (v1.1) and (V1.1). When checking out this repo on a Mac I only get the file with the lowercase v1.1 because it overwrites the V1.1 as the filesystem sees no difference between the two. I suggest either avoiding multiple arts for a single game, or naming them with a greater difference than upper/lowercase.

**Comment by Axiphel** [comment]
This is my fault. :( Alundra's box art wasn't pulling for me because the filename V1.1 didn't match the database casing of v1.1 so I added one without realizing one already existed just with improper naming. Pretty sure the one I added is the game manual art and not the actual box art anyway.

**Comment by cfillak** [comment]
No worries! It gave me a reason to stumble upon the fact that HFS+ is case-insensitive (wtf). I just put in a pull request that changes them to (outer) and (inner) instead of (v1.1) and (V1.1). What database is it calling for PSX? There's no "No-Intro" PSX set/ DAT file, correct?

**Comment by Axiphel** [comment]
There is 'Redump' for PSX which is basically the equivalent of No-Intro.

**Comment by markwkidd** [comment]
Good to know that Redump is the database. That's not in the public docs and in fact it's just been coming up in the forums. I'll add that information to the Lakka  wiki and post in the forum.

**Comment by markwkidd** [comment]
@Axiphel is there any chance you would be willing to look at the ROMs and BIOSes table and let me know if you see that there any other systems currently listed as database unknown that actually do have a set/database?

Here's the table: https://github.com/libretro/Lakka/wiki/ROMs-and-BIOSes#rom-and-bios-requirements-table

**Comment by Axiphel** [comment]
Just the PSP. It uses No-Intro database.

**Comment by markwkidd** [comment]
That helps. Thanks!

**Comment by RobLoach** [comment]
The DAT is over at:
https://github.com/libretro/libretro-database/blob/master/dat/Sony%20-%20PlayStation.dat#L1669

The fix, by @Axiphel, is at:
https://github.com/libretro/libretro-thumbnails/commit/1a956d2d339650a073a7b71129ee0a9782115939

**Comment by RobLoach** [comment]
Can we close this? Anyone on a mac test this?

**Comment by markwkidd** [comment]
I was working on a similar project & on an OS X host so I decided to check on this Alundra thumbnail issue. It seems that the fix was only run on two of the three thumbnail folders -- Named_Snaps still needed to have the 'v' character lower-cased.

I just filed a PR to take care of the remaining rename: https://github.com/libretro/libretro-thumbnails/pull/152

**Comment by lasers** [comment]
Close this?
