### ISSUE TITLE
Boxart for different world region

### ISSUE THREAD

**Issue by lollo78** [libretro/libretro-thumbnails#9]
Hi guys!
I'm cloning the new repository: hope to find some spare time to help you again. 

But before to reprise, I need some indication.

Often, a game released also for Korean, Japanese, Brazil... market has different covers, but for this region sometimes is impossible to find online a good quality boxart to use (most of the time they are totally missing).

For Sega Master System MkIII (incompleted at the moment) I used a different approach from the job done before, trying to respect the regional covers. But this became quickly a very, very, very frustrating job.

So, how should we behave?
My proposal: we could use only EU/USA boxarts also for the games released for different markets and integrate the specific regional covers only for the exclusive games released for the non EU/USA markets.
What do you think?

**Comment by Kivutar** [comment]
I think it's better to have the original covers even for korean games. However, if this cover is impossible to find, it's better than nothing to have the corresponding european or american one. As long as it is temporary.

**Comment by lollo78** [comment]
Thx kivutar!
The cloning failed on Windows with SourceTree:
[log.txt](https://github.com/libretro/libretro-thumbnails/files/243793/log.txt)
Any advice before to try with Linux?

**Comment by Alcaro** [comment]
> error: unable to create file FB Alpha - Arcade Games/Named_Snaps/Adventure Quiz 2 - Hatena? no Daibouken (Japan 900228).png (Invalid argument)
> error: unable to create file FB Alpha - Arcade Games/Named_Snaps/Ambush (hack?).png (Invalid argument)
> error: unable to create file FB Alpha - Arcade Games/Named_Snaps/JoJo's Bizarre Adventure: Heritage for the Future - JoJo no Kimyou na Bouken: Mirai e no Isan (Euro 990913, NO CD).png (Invalid argument)

@Kivutar, don't use \ : ? " | < > in filenames. I know we'd prefer nog caring about Windows, but we have to.

**Comment by sergiobenrocha2** [comment]
You are saying to use USA/Europe covers for Japanase roms, for example? If it's that, it'll be a mess I think.

**Comment by Kivutar** [comment]
OK, we remove those special characters from the DAT and the image names then?

**Comment by Alcaro** [comment]
Remove, replace with underscore, replace with something else, doesn't really matter as long as it's still clear what game it refers to.

Most colons can be replaced with a dash, nobody cares about the difference between "Super Mario World 2: Yoshi's Island" and "Super Mario World 2 - Yoshi's Island". There are some filenames containing both colon and dash, like "JoJo's Bizarre Adventure: Heritage for the Future - JoJo no Kimyou na Bouken: Mirai e no Isan", but we could just remove the Japanese title from those.

Most of the question marks are in random tags, like (hack?) or [Bad sound?], that don't really belong outside a ROM cleaning utility; we can safely remove those and repoint all versions of the same game to the same screenshots. The last two question marks, Adventure Quiz 2 - Hatena? no Daibouken and Athena no Hatena ?, can be removed as well.

**Comment by lollo78** [comment]
@sergiobenrocha2
I'll try to explain better my point of view...
 
All the images, originally scraped from TGDB when we started the project, needs to be manually checked: some boxarts are associated in the wrong way and in most case the Non USA/EU roms (Japanese, Korean...) use the USA/EU.

I think that create the perfect "Wikipedia boxart" is pretty impossible.
I'm sure that I'll die before to see it completed :D

This because find the exact images for each roms region is not always feasible.
After a lot of search you could find the right images but with a poor resolution (the original idea was to create a boxart collection with the better quality available), or you could spend a lot of time to explore the most distant corners of the Web without success. 

So, the "Wikipedia" approach implies an immense work, and we could not associate an image to all the roms. We must make a choice. How to cover the missing images or the poor quality image to the non-US/EU roms?

But the "final boss" spoke: 
> I think it's better to have the original covers even for korean games. However, if this cover is impossible to find, it's better than nothing to have the corresponding european or american one. As long as it is temporary.
I'll do so!
;)

**Comment by sergiobenrocha2** [comment]
For the most common games there's always good scans out there, but I agree we should use the USA covers for the obscure games.

Btw, why are there covers for beta games? This is a thing I vote to remove, most users don't use beta and they don't have box art at all. Snaps and Titles for them is OK.

**Comment by lollo78** [comment]
I think too that the users don't use beta if a stable roms is available, but in my opinion we have to mantain intact the no-intro collection. So, we have to add an image for each roms inside No-Intro-Collection_2016-01-03_Fixed.
This is not an huge job: for beta boxarts we can use the image provided for the stable one.

**Comment by Alcaro** [comment]
See also #19.

**Comment by markwkidd** [comment]
@lollo78 there is now a much more comprehensive system for tracking the thumbnails that are needed. For example, this now exists: https://github.com/RobLoach/libretro-thumbnails-check/blob/master/out/README.md#libretro-thumbnails-check-report

Is this issue ready to be closed?
